# Generated by Django 6.0.3 on 2026-04-17 11:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("education", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AlterField(
            model_name="education",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True,
                help_text="Description optionnelle "
                "(résultats, projets, mentions, etc.).",
                verbose_name="Content",
            ),
        ),
    ]
