# Generated by Django 6.0.3 on 2026-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_projectcategory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TestModel",
        ),
    ]
