# Generated by Django 6.0.3 on 2026-05-18 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0004_tag_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.ForeignKey(
                help_text="Catégorie du projet",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="project.projectcategory",
            ),
        ),
    ]
