# Generated by Django 6.0.3 on 2026-05-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='published_at',
            field=models.DateField(blank=True, help_text="Date de publication de l'article", null=True),
        ),
    ]
