# Generated by Django 6.0.3 on 2026-04-14 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date']},
        ),
    ]
