# Generated by Django 6.0.3 on 2026-04-30 11:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la catégorie de projet.', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création de la catégorie.')),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire des catégories de projets.', on_delete=django.db.models.deletion.CASCADE, related_name='project_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Nom du projet.', max_length=200)),
                ('start_date', models.DateField(help_text='Date de debut du projet')),
                ('end_date', models.DateField(blank=True, help_text='Date de fin du projet', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Statut du projet (actif/inactif)')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création du projet')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière mise à jour du projet')),
                ('source_code_url', models.URLField(blank=True, help_text='URL du code source du projet', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image du projet', null=True, upload_to='projects/images/')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Détails complets du projet.', verbose_name='Content')),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire des projets.', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
