# Generated by Django 6.0.3 on 2026-05-12 12:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0007_alter_applicationfollowup_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="applicationfollowup",
            options={
                "ordering": ["event_date"],
                "verbose_name": "Élément de suivi",
                "verbose_name_plural": "Éléments de suivi",
            },
        ),
        migrations.RenameField(
            model_name="applicationfollowup",
            old_name="date",
            new_name="event_date",
        ),
    ]
