# Generated by Django 6.0.3 on 2026-04-13 13:16

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userprofile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=django_ckeditor_5.fields.CKEditor5Field(
                blank=True, verbose_name="Content"
            ),
        ),
    ]
