# Generated by Django 6.0.3 on 2026-04-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('techstack', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='techstackcategory',
            options={'ordering': ['order']},
        ),
    ]
