# Generated by Django 6.0.3 on 2026-04-28 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Le nom de la certification', max_length=255)),
                ('issuer', models.CharField(blank=True, help_text="L'organisme qui a délivré la certification ou lien vers le certificat", max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('user', models.ForeignKey(help_text='Utilisateur propriétaire de la certification', on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
